-- MySQL Script generated by MySQL Workbench
-- Пт 15 янв 2021 16:28:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shema` DEFAULT CHARACTER SET utf8 ;
USE `shema` ;

-- -----------------------------------------------------
-- Table `shema`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`category` (
  `id_category` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NOT NULL,
  `symbol_code` CHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `symbol_code_UNIQUE` (`symbol_code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shema`.`lots_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`lots_list` (
  `id_lots_storage` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lot_item_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_lots_storage`),
  INDEX `lot_id_idx` (`lot_item_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `lots_list_lot_id`
    FOREIGN KEY (`lot_item_id`)
    REFERENCES `shema`.`lot` (`id_lot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lots_list_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shema`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shema`.`bet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`bet` (
  `id_bet` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_creation` DATETIME NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `lot_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_bet`),
  INDEX `uder_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `lot_id_idx` (`lot_id` ASC) VISIBLE,
  CONSTRAINT `bet_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shema`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bet_lot_id`
    FOREIGN KEY (`lot_id`)
    REFERENCES `shema`.`lot` (`id_lot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shema`.`bets_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`bets_list` (
  `id_bets_list` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bet_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_bets_list`),
  INDEX `bet_id_idx` (`bet_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `bets_list_bet_id`
    FOREIGN KEY (`bet_id`)
    REFERENCES `shema`.`bet` (`id_bet`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bets_list_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shema`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`user` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration_date` DATETIME NOT NULL,
  `email` CHAR(255) NOT NULL,
  `name` CHAR(255) NOT NULL,
  `passwd` CHAR(64) NOT NULL,
  `contact_info` VARCHAR(512) NOT NULL,
  `lots_id` INT UNSIGNED NOT NULL,
  `bets_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `lots_id_idx` (`lots_id` ASC) VISIBLE,
  INDEX `bets_id_idx` (`bets_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `user_lots_id`
    FOREIGN KEY (`lots_id`)
    REFERENCES `shema`.`lots_list` (`id_lots_storage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_bets_id`
    FOREIGN KEY (`bets_id`)
    REFERENCES `shema`.`bets_list` (`id_bets_list`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shema`.`lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shema`.`lot` (
  `id_lot` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_creation` DATETIME NOT NULL,
  `name` CHAR(255) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  `img_src` CHAR(255) NOT NULL,
  `starter_price` INT UNSIGNED NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `bet_offset` INT UNSIGNED NOT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `winner_id` INT UNSIGNED NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_lot`),
  INDEX `author_id_idx` (`author_id` ASC) VISIBLE,
  INDEX `winner_id_idx` (`winner_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `lot_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `shema`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lot_winner_id`
    FOREIGN KEY (`winner_id`)
    REFERENCES `shema`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lot_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `shema`.`category` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
